#include "device_driver.h"
#include "view.h"

char restore[101];


void initView()
{
	Lcd_Half_Clr_Screen(1);

	Lcd_Printf(TITLE_X_START, TITLE_Y_START, WHITE, BLACK, TITLE_TEXT_SIZE, TITLE_TEXT_SIZE, "은하수를 여행하는 히치하이커를 위한  번역기");
	Lcd_Draw_Bar( INIT_INPUTBOX_X, INIT_INPUTBOX_Y, END_INPUTBOX_X, END_INPUTBOX_Y, WHITE);
	Lcd_Draw_Bar( INIT_INPUTBOX_X + LINE_SIZE, INIT_INPUTBOX_Y + LINE_SIZE, END_INPUTBOX_X - LINE_SIZE, END_INPUTBOX_Y - LINE_SIZE, BLACK);
	Lcd_Printf(BOX1_TITLE_X_START, BOX1_TITLE_Y_START, WHITE, BLACK, BOX_TEXT_SIZE, BOX_TEXT_SIZE, " INPUT ");

	Lcd_Draw_Bar( INIT_OUTPUTBOX_X, INIT_OUTPUTBOX_Y, END_OUTPUTBOX_X, END_OUTPUTBOX_Y, WHITE);
	Lcd_Draw_Bar( INIT_OUTPUTBOX_X + LINE_SIZE, INIT_OUTPUTBOX_Y + LINE_SIZE, END_OUTPUTBOX_X - LINE_SIZE, END_OUTPUTBOX_Y - LINE_SIZE, BLACK);
	Lcd_Printf(BOX2_TITLE_X_START, BOX2_TITLE_Y_START, WHITE, BLACK, BOX_TEXT_SIZE, BOX_TEXT_SIZE, " OUTPUT ");
}

void printOutPut(char* outPut)
{
	Lcd_Printf(OUTPUT_X_START, OUTPUT_Y_START, WHITE, BLACK, INNER_TEXT_SIZE, INNER_TEXT_SIZE, "%s", outPut);
}

void printInPut(char* inPut)
{
	Lcd_Printf(INPUT_X_START, INPUT_Y_START, WHITE, BLACK, INNER_TEXT_SIZE, INNER_TEXT_SIZE, "%s", inPut);
}

void clearView()
{
	Lcd_Draw_Bar( INIT_INPUTBOX_X + LINE_SIZE, INIT_INPUTBOX_Y + LINE_SIZE, END_INPUTBOX_X - LINE_SIZE, END_INPUTBOX_Y - LINE_SIZE, BLACK);
	Lcd_Printf(BOX1_TITLE_X_START, BOX1_TITLE_Y_START, WHITE, BLACK, BOX_TEXT_SIZE, BOX_TEXT_SIZE, " INPUT ");

	Lcd_Draw_Bar( INIT_OUTPUTBOX_X + LINE_SIZE, INIT_OUTPUTBOX_Y + LINE_SIZE, END_OUTPUTBOX_X - LINE_SIZE, END_OUTPUTBOX_Y - LINE_SIZE, BLACK);
	Lcd_Printf(BOX2_TITLE_X_START, BOX2_TITLE_Y_START, WHITE, BLACK, BOX_TEXT_SIZE, BOX_TEXT_SIZE, " OUTPUT ");
}
